services:
  db:
    image: postgres:latest
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5433:5432"
    volumes:
      - sonar_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonar -d sonar" ]
      interval: 5s
      timeout: 5s
      retries: 10
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 10

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - --hub-mode=off
      - --changeLogFile=db/changelog/db.changelog-master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/mydatabase
      - --username=postgres
      - --password=mysecretpassword
      - update
    volumes:
      - ./server/src/main/resources:/liquibase/changelog

  server:
    depends_on:
      postgres:
        condition: service_healthy
      liquibase-migrations:
        condition: service_completed_successfully
    build:
      context: .
    container_name: server_container
    ports:
      - "12345:12345/udp"
    volumes:
      - ./logs:/logs
volumes:
  postgres:
  sonar_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: