name: CI

on:
  push:
    branches: [ "" ]
  pull_request:
    branches: [ "" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests with JaCoCo
        run: mvn clean verify --batch-mode -Djacoco.skip=false

      - name: Upload JaCoCo XML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-html
          path: target/site/jacoco/

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/