name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Можно выбрать 'adopt', 'zulu' и другие
          java-version: '17'

      # 3. Кэширование зависимостей Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Сборка проекта с помощью Maven
      - name: Build with Maven
        run: mvn clean install --batch-mode --show-version
